# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wirecat.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Wirecat(object):
    def setupUi(self, Wirecat):
        Wirecat.setObjectName("Wirecat")
        Wirecat.resize(1036, 600)
        self.centralwidget = QtWidgets.QWidget(Wirecat)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(100, 20, 901, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label_5.setObjectName("label_5")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 470, 93, 28))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_1.setGeometry(QtCore.QRect(80, 470, 93, 28))
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(220, 470, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(40, 90, 941, 341))
        self.tableWidget.setMaximumSize(QtCore.QSize(951, 16777215))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        Wirecat.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(Wirecat)
        self.statusbar.setObjectName("statusbar")
        Wirecat.setStatusBar(self.statusbar)

        self.retranslateUi(Wirecat)
        QtCore.QMetaObject.connectSlotsByName(Wirecat)

    def retranslateUi(self, Wirecat):
        _translate = QtCore.QCoreApplication.translate
        Wirecat.setWindowTitle(_translate("Wirecat", "MainWindow"))
        self.label_5.setText(_translate("Wirecat", "Filter："))
        self.pushButton_3.setText(_translate("Wirecat", "Pack"))
        self.pushButton_1.setText(_translate("Wirecat", "Start"))
        self.pushButton_2.setText(_translate("Wirecat", "Stop"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Wirecat", "No."))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Wirecat", "Source"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Wirecat", "Destination"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Wirecat", "Proto"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Wirecat", "Length"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Wirecat", "Info"))
        self.tableWidget.setColumnWidth(0, 80)
        self.tableWidget.setColumnWidth(1, 180)
        self.tableWidget.setColumnWidth(2, 180)
        self.tableWidget.setColumnWidth(3, 80)
        self.tableWidget.setColumnWidth(4, 80)
        self.tableWidget.setColumnWidth(5, 339)

